# Generated by Django 5.0.2 on 2024-02-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_client_address_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportist',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido'),
        ),
    ]
